// manifest.js — 自动生成的资产清单（game/assets/ 下全部文件）
export const ASSET_FILES = [
  "building_names.json",
  "buildings/bank.png",
  "buildings/bar.png",
  "buildings/cemetery.png",
  "buildings/church.png",
  "buildings/dry_dock.png",
  "buildings/fortune_house.png",
  "buildings/harbor.png",
  "buildings/home.png",
  "buildings/inn.png",
  "buildings/item_shop.png",
  "buildings/job_house.png",
  "buildings/market.png",
  "buildings/msc.png",
  "buildings/palace.png",
  "buildings/teacher.png",
  "discoveries.png",
  "dos/duke.png",
  "dos/hero_ali.png",
  "dos/hero_catalina.png",
  "dos/hero_ernst.png",
  "dos/hero_hero_b1.png",
  "dos/hero_hero_b2.png",
  "dos/hero_hero_b3.png",
  "dos/hero_joao.png",
  "dos/hero_otto.png",
  "dos/hero_pietro.png",
  "dos/scene_opening.png",
  "dos/scene_tavern.png",
  "dos/ui_dialogbox.png",
  "dos/ui_yesno.png",
  "figures.png",
  "goods.json",
  "heroes.png",
  "maids.json",
  "mates.json",
  "music/battle.ogg",
  "music/building/bar.mp3",
  "music/building/church.mp3",
  "music/building/msc.mp3",
  "music/building/palace.mp3",
  "music/port.ogg",
  "music/port/African Town.mp3",
  "music/port/Amsterdam.mp3",
  "music/port/Central America Town.mp3",
  "music/port/China Town.mp3",
  "music/port/Faro.mp3",
  "music/port/Indian Town.mp3",
  "music/port/Japan Town.mp3",
  "music/port/Lisbon.mp3",
  "music/port/London.mp3",
  "music/port/Marseille.mp3",
  "music/port/Middle Eastern Town.mp3",
  "music/port/Northern Europe Town.mp3",
  "music/port/Oceania Town.mp3",
  "music/port/Seville.mp3",
  "music/port/South America Town.mp3",
  "music/port/Southeast Asian Town.ogg",
  "music/port/Southern Europe Town.mp3",
  "music/port/Venice.mp3",
  "music/sea.ogg",
  "music/sea/African Sea.mp3",
  "music/sea/American Sea.mp3",
  "music/sea/Atlantic Ocean.mp3",
  "music/sea/East Asia Sea.mp3",
  "music/sea/Indian Ocean.mp3",
  "music/sea/Mediterranean.mp3",
  "music/sea/North Sea.mp3",
  "music/sea/Pacific.mp3",
  "music/sea/Southeast Asian Sea.ogg",
  "music/sea_1.ogg",
  "npc_atlas.png",
  "person-tileset.png",
  "port_meta.json",
  "portchips/000_dawn.png",
  "portchips/000_day.png",
  "portchips/000_dusk.png",
  "portchips/000_night.png",
  "portchips/002_dawn.png",
  "portchips/002_day.png",
  "portchips/002_dusk.png",
  "portchips/002_night.png",
  "portchips/004_dawn.png",
  "portchips/004_day.png",
  "portchips/004_dusk.png",
  "portchips/004_night.png",
  "portchips/006_dawn.png",
  "portchips/006_day.png",
  "portchips/006_dusk.png",
  "portchips/006_night.png",
  "portchips/008_dawn.png",
  "portchips/008_day.png",
  "portchips/008_dusk.png",
  "portchips/008_night.png",
  "portchips/010_dawn.png",
  "portchips/010_day.png",
  "portchips/010_dusk.png",
  "portchips/010_night.png",
  "portchips/012_dawn.png",
  "portchips/012_day.png",
  "portchips/012_dusk.png",
  "portchips/012_night.png",
  "portmaps.bin",
  "ports.json",
  "ruins.json",
  "ship-tileset.png",
  "ships.json",
  "ships/balsa.png",
  "ships/barge.png",
  "ships/brigantine.png",
  "ships/buss.png",
  "ships/caravela latina.png",
  "ships/caravela redonda.png",
  "ships/carrack.png",
  "ships/dhow.png",
  "ships/flemish galleon.png",
  "ships/frigate.png",
  "ships/full rigged ship.png",
  "ships/galleon.png",
  "ships/hansa cog.png",
  "ships/junk.png",
  "ships/la reale.png",
  "ships/light galley.png",
  "ships/nao.png",
  "ships/pinnace.png",
  "ships/sloop.png",
  "ships/talette.png",
  "ships/venetian galeass.png",
  "ships/xebec.png",
  "sounds/discover.ogg",
  "sounds/engage.ogg",
  "sounds/explosion.ogg",
  "sounds/shoot.ogg",
  "sounds/wave.ogg",
  "tiles_dawn.png",
  "tiles_day.png",
  "tiles_dusk.png",
  "tiles_night.png",
  "towns.json",
  "villages.json",
  "waifu/barbara.png",
  "waifu/eudora.png",
  "waifu/isabella.png",
  "waifu/mita.png",
  "waifu/sophia.png",
  "world_map.bin",
];
